### PR TITLE
#6: Migrate DB layer to sqlx and pq for PostgreSQL Support

### PR DESCRIPTION
**Pull request by Jalmeida1994**
This pull request introduces several significant updates, including a transition from SQLite to PostgreSQL, enhancements to the development setup, and the addition of pagination support for various API endpoints. 

- Add docker-compose for postgreSQL DB local development support
- Pagination for list requests

~~TODO: add context.Context to support cancellation and timeouts in DB requests.~~

### CODE REVIEW

**Comment by Jalmeida1994** [comment]
And I need to rebase the latest changes too.

**Comment by Jalmeida1994** [comment]
Just rebased the latest changes. Still need to add the User API endpoints to fully test the user stuff

**Comment by Jalmeida1994** [comment]
I'll mark this one as ready to review. It's still missing the context to handle cancellations and timeouts. Also transactions support and query building but as we still want to check out externalizing SQL queries via https://github.com/knadh/goyesql I would probably check it out then. This PR is already too large.

I also changed the IMAP server port to 1143 as 1025 was already being used by the mail server.

**Comment by Jalmeida1994** [comment]
I also added main.go inside `cmd/mercury`: https://github.com/lmmendes/mercury/blob/6-migrate-database-layer-to-sqlx-and-pq-for-postgresql-production-support/cmd/mercury/main.go

However I'm still unsure. Feels weird but it seems that cmd folder is for application entrypoint

**Review by lmmendes — APPROVED** [review]

**Pull request merged**
